services:
  frontend:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
      args:
        - BACKEND_URL="http://localhost:9428"
    ports:
      - '8080:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - databaseBackVol:/home/node/app/database
    healthcheck:
      test: curl -f http://localhost:9428/api/status | grep "ok" || exit 1
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
  
volumes:
  databaseBackVol:


